---
  - name: Initializing software upgrade on IOS routers
    hosts: iosswitchbranchupgrade
    gather_facts: no

    vars:
      upgrade_ios_version: 15.2(2)E6
      new_ios_file_name: c2960x-universalk9-mz.152-2.E6.bin

    tasks:
      - name: Reboot in progress...please standby
        ansible.builtin.wait_for:
          timeout: 360
