---
- name: initializing resource facts collection
  hosts: iosrouterbranch

  tasks:
    - name: resource facts
      cisco.ios.ios_facts:
        gather_subset:
        - '!config'
    - debug:
        msg:
        - "Device Hostname:         '{{ ansible_net_hostname }}'"
        - "Device Model:            '{{ ansible_net_model }}'"
        - "Device Software Version: '{{ ansible_net_version }}'"
        - "Device Serial Number:    '{{ ansible_net_serialnum }}'"
        - "Device Software:         '{{ ansible_net_image }}'"
