---
  - name: Initializing software upgrade on IOS routers
    hosts: iosswitchbranchupgrade
    gather_facts: no

    vars:
      upgrade_ios_version: 15.2(2)E6
      new_ios_file_name: c2960x-universalk9-mz.152-2.E6.bin

    tasks:
      - name: Checking current OS version
        cisco.ios.ios_facts:
      - debug:
          msg:
          - "Current version is {{ ansible_net_version }}"
          - "Upgrade image is 15.2(2)E6"
      - debug:
          msg:
          - "Image is not compliant and will be upgraded"
        when: ansible_net_version != upgrade_ios_version

      - name: Initilizing old OS removal
        ios_command:
          commands:
          - "configure terminal"
          - "file prompt quiet"

      - name: Completed old OS removal
        ios_command:
          commands:
          - "configure terminal"
          - "no file prompt quiet"

      - name: Enabling ssh output transport to pull IOS from remote repository
        ios_command:
          commands:
          - "configure terminal"
          - "line vty 0 4"
          - "transport output ssh"

      - name: Please standby..recommended IOS upload is in progress
        cli_command:
          command: copy scp://admin@172.22.0.100/{{ new_ios_file_name }} flash:{{ new_ios_file_name }}
          check_all: true
          prompt:
          - 'Destination filename'
          - 'Password'
          answer:
          - '{{ new_ios_file_name }}'
          - 'Apple@123'
        vars:
          ansible_command_timeout: 600

      - name: Checking MD5 Sum of new OS
        ios_command:
          commands:
          - "verify /md5 {{ new_ios_file_name }}"
          wait_for:
          - result[0] contains "3a1db74f663e0b5601b6a2ae22cdf3a7"
          retries: 1
        vars:
          ansible_command_timeout: 120

      - name: Disabling ssh output transport on vty line
        ios_command:
          commands:
          - "configure terminal"
          - "line vty 0 4"
          - "transport output none"
          - "exit"
          - "exit"

      - name: Adding new boot variable
        cisco.ios.ios_config:
          lines:
            - boot system flash:c2960x-universalk9-mz.152-2.E6.bin
          save_when: always

      - name: Reload
        cli_command:
          command: reload
          prompt:
            - confirm
          answer:
            - 'y'

      - name: Reboot in progress...please standby
        ansible.builtin.wait_for:
          port: 22
          state: started
          delay: 450
          host: "{{ inventory_hostname }}"
        delegate_to: localhost

      - name: Check Image Version      
        ios_facts:
      - debug:
          msg:
          - "Current version is {{ ansible_net_version }}"
      - name: Assert router is upgraded to recommended OS
        assert:
          that:
            - upgrade_ios_version == ansible_net_version
      - debug:
          msg:
          - "Software Upgrade has been completed"
