---
  - name: Initializing software upgrade on IOS routers
    hosts: iosswitchbranchupgrade
    gather_facts: no

    vars:
      upgrade_ios_version: 15.2(7)E6
      new_ios_file_name: c2960x-universalk9-mz.152-7.E6.bin

    tasks:
      - name: Adding new boot variable
        cisco.ios.ios_config:
          lines:
            - boot system flash:c2960x-universalk9-mz.152-7.E6.bin
          save_when: always

      - name: Reload
        cli_command:
          command: reload
          prompt:
            - confirm
          answer:
            - 'y'

      - name: Reboot in progress...please standby
        ansible.builtin.wait_for:
          host: "{{ inventory_hostname }}"
          port: 22
          delay: 400
          timeout: 460
        delegate_to: localhost
        
      - name: Check Image Version
        ios_facts:
      - debug:
          msg:
          - "Current version is {{ ansible_net_version }}"
      - name: Assert device is upgraded to recommended OS
        assert:
          that:
            - upgrade_ios_version == ansible_net_version
      - debug:
          msg:
          - "Software Upgrade has been completed"
